# Generated by Django 5.0.7 on 2024-07-31 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='introduction',
            field=models.TextField(blank=True, help_text='Brief introduction to the post'),
        ),
    ]
