# Generated by Django 5.0.7 on 2024-08-13 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
